export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";


export const AFTER_REGISTER_SUCCESS = "AFTER_REGISTER_SUCCESS";

export const AUTO_LOGIN = "AUTO_LOGIN";


export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";



export const CREATE_PROFILE = "CREATE_PROFILE";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAILURE = "CREATE_PROFILE_FAILURE";

export const FETCH_PROFILE_REQUEST = "FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_RESPONSE = "FETCH_PROFILE_RESPONSE";


export const FETCH_PROFILE_BY_ID_REQUEST = "FETCH_PROFILE_BY_ID_REQUEST";
export const FETCH_PROFILE_BY_ID_RESPONSE = "FETCH_PROFILE_BY_ID_RESPONSE";
export const FETCH_PROFILE_BY_ID_FAILURE = "FETCH_PROFILE_BY_ID_FAILURE";






export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const UPLOAD_PHOTO_SUCCESS = "UPLOAD_PHOTO_SUCCESS";
export const UPLOAD_PHOTO_FAILURE = "UPLOAD_PHOTO_FAILURE";



export const CREATE_COMPANY = "CREATE_COMPANY";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAILURE = "CREATE_COMPANY_FAILURE";

export const FETCH_COMPANY = "FETCH_COMPANY";
export const FETCH_COMPANY_SUCCESS = "FETCH_COMPANY_SUCCESS";
export const FETCH_COMPANY_FAILURE = "FETCH_COMPANY_FAILURE";




export const FETCH_COMPANY_BY_USER_ID = "FETCH_COMPANY_BY_USER_ID";
export const FETCH_COMPANY_SUCCESS_BY_USER_ID = "FETCH_COMPANY_SUCCESS_BY_USER_ID";
export const FETCH_COMPANY_FAILURE_BY_USER_ID = "FETCH_COMPANY_FAILURE_BY_USER_ID";





export const SET_INITIAL_LOADING = "SET_INITIAL_LOADING";


export const CLEAR_STORE = "CLEAR_STORE";



